#!/bin/bash

if [[ "$CI" != 'true' ]]; then
    echo 'Exporting build environment variables...'
    export SDK='iphonesimulator11.1'
    export WORKSPACE='SwiftUtils.xcworkspace'
    export DESTINATION='OS=11.1,name=iPhone 6'
fi

xcodebuild build \
    -workspace "$WORKSPACE" \
    -scheme "PodTest" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration Debug | bundle exec xcpretty; exit ${PIPESTATUS[0]}
