#!/bin/bash

if [[ "$CI" != 'true' ]]; then
    echo 'Exporting build environment variables...'
    export WORKSPACE='SwiftUtils.xcworkspace'
    export SDK='iphonesimulator11.2'
    export SCHEME='Framework'
    export DESTINATION='OS=11.2,name=iPhone 6'
fi

rm -rf './build'

xcodebuild build test \
    -workspace "$WORKSPACE" \
    -scheme "$SCHEME" \
    -sdk "$SDK" \
    -destination "$DESTINATION" \
    -derivedDataPath build \
    ONLY_ACTIVE_ARCH=YES \
    -configuration Debug | bundle exec xcpretty; exit ${PIPESTATUS[0]}
